FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less file
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential
# RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libbigwig-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake pkg-config libtool
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libz-dev libbz2-dev liblzma-dev

RUN git clone https://github.com/samtools/htslib --recursive
WORKDIR /htslib
RUN autoreconf -if
RUN ./configure
RUN make -j8 && make install
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libcurl4-openssl-dev

WORKDIR /
RUN git clone https://github.com/dpryan79/libBigWig
WORKDIR /libBigWig
RUN make -j8 && make install

COPY . /repo
WORKDIR /repo
# RUN make -j8
